version: '3.8'

services:
  lint:
    build:
      context: .
      dockerfile: DockerfileForDockerCompose
    image: ${TEXT_LINT_IMAGE_NAME}:${TEXT_LINT_IMAGE_TAG}
    volumes:
      - .:/workspaces/daigirin-template
      - /workspaces/daigirin-template/node_modules
    working_dir: /workspaces/daigirin-template
    command: yarn lint
